### ISSUE TITLE
Kesalahan Pada Indicator ketika digunakan bersama framework materialize css

### ISSUE THREAD

**Issue by MuhamadIchsan** [Carousnap/carousnap.github.io#1]
maaf,plugin ini memang tidak bisa digunakan bersama framework css lain atau bagaimana ya? karena ketika pluginnya digunakan bersamaan dengan framework materialize css,ada  sedikit masalah pada indicatornya
![error2PNG](https://user-images.githubusercontent.com/57169888/103460582-e7181a80-4d49-11eb-8ce7-c695eead596c.PNG)
![errorPNG](https://user-images.githubusercontent.com/57169888/103460583-e97a7480-4d49-11eb-9f0f-09537a3c6c0a.PNG)

**Comment by Carousnap** [comment]
Wahh kayaknya memang ada bentrok di bagian css nya .. 
Makasi penemuannya bro 😀 .. Oh ya klw ada issue lagi tambahkan ke sini aja ✌️ .. 

https://github.com/Carousnap/carousnap/issues

**Comment by Carousnap** [comment]
> maaf,plugin ini memang tidak bisa digunakan bersama framework css lain atau bagaimana ya? karena ketika pluginnya digunakan bersamaan dengan framework materialize css,ada sedikit masalah pada indicatornya
> ![error2PNG](https://user-images.githubusercontent.com/57169888/103460582-e7181a80-4d49-11eb-8ce7-c695eead596c.PNG)
> ![errorPNG](https://user-images.githubusercontent.com/57169888/103460583-e97a7480-4d49-11eb-9f0f-09537a3c6c0a.PNG)

=============================
Sudah di Solved gan,  Check CarouSnap@v.1.3 terbaru .. kalau tidak keberatan boleh dicoba lagi. dan jangan sungkan apabila ada kesalahan yang lain. 😀 Terimah Kasih gan
